### ISSUE TITLE
Change of Logo

### ISSUE THREAD

**Issue by mindingdata** [matijarmk/dotnet-core-commands#7]
Hey there, 

I like the extension. Do you mind changing the logo on the marketplace for me :)

**Comment by matijarmk** [comment]
sure thing do

**Comment by matijarmk** [comment]
we can do that for sure :) just pull request it

**Comment by mindingdata** [comment]
Well, I'm more meaning that I run https://dotnetcoretutorials.com/

And your logo here : https://marketplace.visualstudio.com/items?itemName=matijarmk.dotnet-core-commands

Is a liiitttlleee bit too similar :)

**Comment by matijarmk** [comment]
Changed :)
